apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gitops-demo
  name: gitops-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: gitops-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gitops-demo
    spec:
      containers:
      - image: bibhas2/gitops-demo-webapp
        name: gitops-demo
        resources: {}
